name: flutter_project_team1
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^14.2.0 # 페이지 이동
  flutter_riverpod: ^2.5.1 #상태관리
  flutter_svg: ^2.0.10+1 # svg 사용
  flutter_bloc: ^8.1.6 # bloc, cubit

  english_words: ^4.0.0
  dart_code_metrics_presets: ^2.13.0 #dart code 규칙관련
  google_fonts: ^6.2.1 #font
  file_picker: ^8.0.5
  dots_indicator: ^3.0.0 #홈화면-indicator
  image_picker: ^1.1.2 # 제품등록
  cached_network_image: ^3.3.1 # network image 사용
  flutter_image_compress: ^2.3.0 # 이미지 용량 압축
  intl: ^0.19.0 #데이터 포맷

  fluttertoast: ^8.0.8 # 토스트 팝업 사용
  provider: ^6.0.3 # Provider 사용
  kpostal: ^0.5.1 # 카카오Map과 버전 충돌로 remedi_kopo 대체...
  kakao_map_plugin: ^0.3.1 #카카오 Map
  flutter_config: ^2.0.2 # .env 파일 Api Key 입력 후 사용..
  shared_preferences: ^2.2.3

  #freezed
  freezed_annotation: ^2.4.1 # 데이터 모델
  json_annotation: ^4.9.0 #json 변환

  http: ^1.2.1 #Http 통신, 크롤링
  retrofit: ^4.1.0   #Retrofit
  dio: ^5.4.3+1 #Dio
  get_it: ^7.7.0
  mocktail: ^1.0.4
  url_launcher: ^6.3.0

  #firebase
  google_sign_in: ^6.2.1 #구글로그인
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  firebase_storage: ^12.1.0
  cloud_firestore: ^5.0.2
  firebase_database: ^11.0.2
  logger: ^2.3.0

  # 로그인 관련
  kakao_flutter_sdk_user: ^1.9.3 # 카카오 로그인 API 패키지
  flutter_naver_login: ^1.8.0 # 네이버 로그인

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  freezed: ^2.5.2 # 데이터 모델
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

  retrofit_generator: ^8.1.1


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/svg/
    - assets/icon/
    - assets/images/
    - assets/fonts/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Dongle
      fonts:
        - asset: assets/fonts/Dongle-Light.ttf
          weight: 200
        - asset: assets/fonts/Dongle-Regular.ttf
          weight: 400
        - asset: assets/fonts/Dongle-Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
